apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

group = 'expo.modules.alipay'
version = '1.0.0'

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()

def safeExtGet(prop, fallback) {
    rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}

android {
    namespace "expo.modules.alipay"
    compileSdkVersion safeExtGet("compileSdkVersion", 33)

    defaultConfig {
        minSdkVersion safeExtGet("minSdkVersion", 21)
        targetSdkVersion safeExtGet("targetSdkVersion", 33)
    }

    publishing {
        multipleVariants {
            withSourcesJar()
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':expo-modules-core')
    
    // 支付宝 SDK
    implementation 'com.alipay.sdk:alipaysdk-android:15.8.16'
}
